pkg/fscrypt: support builds for other ARCHs
Pillar, which is crossbuildable, depends on fscrypt. Without this
cludge any attempt to build pillar for any ARCH other than amd64
raises the following absolutely implicit and opague error:

   Error: error building "lfedge/eve-pillar:f6cd4c5f47f4900781840ea5b861ddecca52c35d": error building for arch arm64: failed to solve: no match for platform in manifest: not found

Which can mean anything. By trials and errors build problems with
the fscrypt were determined.

Signed-off-by: Roman Penyaev <r.peniaev@gmail.com>